#remote_theme: "mmistakes/minimal-mistakes"
#minimal_mistakes_skin: "mint"

theme: jekyll-theme-dinky
name: "Oana Vesa"
description: "Grad Student"
timezone: America/Denver


Hi all! I am a 3rd year Ph.D student at New Mexico State University, where I study how waves/oscillations and atmospheric dynamics affect the solar atmosphere.
