#remote_theme: "mmistakes/minimal-mistakes"
#minimal_mistakes_skin: "mint"

theme: jekyll-theme-dinky
name: Oana Vesa
url: "https://ovesa.github.io"
subtitle: Astronomy PhD Student
description: The ramblings of an astronomy graduate student
permalink: /:categories/:year/:month/:day/:title/

