#remote_theme: "mmistakes/minimal-mistakes"
#minimal_mistakes_skin: "mint"

theme: jekyll-theme-dinky
name: "Oana Vesa"
subtitle: Astronomy PhD Student
description: The ramblings of an astronomy graduate student
timezone: America/Denver

