# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# > # this means to ignore newlines until "baseurl:"

title: Oana Vesa
subtitle: Astronomy PhD Student
email: ovesa@nmsu.edu
#description: "I'm a 3rd year graduate student. I study the propagation and properties of gravity waves with the aim of using them as diagnostics for the average magnetic field."
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
# use https://ovesa.github.io afterwards
#twitter_username: jekyllrb
github_username:  ovesa
description: The ramblings of an astronomy graduate student

# Build settings
#theme: minima
theme: minimal-mistakes-jekyll 
minimal_mistakes_skin: "mint"
gems:
  - jekyll-feed

#site setting
locale: "en-US"


# Site Author
author:
  name: "Oana Vesa"
  avatar: "/images/avatar.png" #path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio 	: "I'm a 3rd year graduate student. I study the propagation and properties of gravity waves with the aim of using them as diagnostics for the average magnetic field."
  location: "NM"
  email:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: ""
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ovesa/"
# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ovesa/"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
