# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# > # this means to ignore newlines until "baseurl:"

title: Astronomy PhD Student
subtitle: Solar Physics
email: ovesa@nmsu.edu
#description: "I'm a 3rd year graduate student. I study the propagation and properties of gravity waves with the aim of using them as diagnostics for the average magnetic field."
baseurl: "/page" # the subpath of your site, e.g. /blog
url: "https://ovesa.github.io" #"localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
# use https://ovesa.github.io afterwards
#twitter_username: jekyllrb
#github_username:  ovesa
description: > # this means to ignore newlines until "show_exerpts:"
  The ramblings of an astronomy graduate student
permalink: /blog/:year/:month/:day/:title/
show_excerpts: true # set to true to show excerpts on the homepage


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Oana
  tagline: graduate student
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/me.jpeg" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  navigation:
    - title: Current Research
      url: "/my-work"
    #- title: Resume
     # url: "/resume"
  # generate social links in footer
  social_links:
    #twitter: samasault
    github:  ovesa
    #linkedIn: in/
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll

# Build settings
#theme: minima
remote_theme: samarsault/plainwhite-jekyll
#theme: plainwhite
#theme: jekyll-theme-dinky
#minimal_mistakes_skin: "mint"
gems:
  - jekyll-feed

#site setting
locale: "en-US"

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
#exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
 #  - Gemfile
 #  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
